#ifndef _ANTENNA_TRACKER_H_
#define _ANTENNA_TRACKER_H_

#ifdef DESKTOP_BUILD
#define CONFIG_ANTENNA_TRACKER_TELEMETRY_CALLSIGN "VA3XXA"
#define CONFIG_ANTENNA_TRACKER_SYSLOG_INFO 1
#define CONFIG_ANTENNA_TRACKER_SYSLOG_DEBUG 1
#define CONFIG_ANTENNA_TRACKER_SYSLOG_ERR 1
#define CONFIG_ANTENNA_TRACKER_SYSLOG_WARN 1
// #define CONFIG_ANTENNA_TRACKER_SYSLOG_PATH "antenna-tracker.log"
#define CONFIG_ANTENNA_TRACKER_MOCKING 1
#endif

#include "syslogging.h"

#endif