include $(APPDIR)/Make.defs

PROGNAME = $(CONFIG_ANTENNA_TRACKER_PROGNAME)
PRIORITY = $(CONFIG_ANTENNA_TRACKER_PRIORITY)
STACKSIZE = $(CONFIG_ANTENNA_TRACKER_STACKSIZE)
MODULE = $(CONFIG_ANTENNA_TRACKER)

MAINSRC = src/tracker.c

include $(APPDIR)/Application.mk