include $(APPDIR)/Make.defs

PROGNAME = $(CONFIG_INSPACE_TRACKER_PROGNAME)
PRIORITY = $(CONFIG_INSPACE_TRACKER_PRIORITY)
STACKSIZE = $(CONFIG_INSPACE_TRACKER_STACKSIZE)
MODULE = $(CONFIG_INSPACE_TRACKER)

MAINSRC = src/tracker.c
CSRCS += $(wildcard src/**/*.c)
CSRCS += $(wildcard src/*.c)

include $(APPDIR)/Application.mk